#ddev-generated
services:
  pdfreactor:
    container_name: ddev-${DDEV_SITENAME}-pdfreactor
    image: realobjects/pdfreactor
    # These labels ensure this service is discoverable by ddev.
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    volumes:
    - ".:/mnt/ddev_config"
    - "./pdfreactor:/ro/config"
    external_links:
    - "ddev-router:${DDEV_SITENAME}.${DDEV_TLD}"
    healthcheck:
      test: ["CMD-SHELL", "curl --fail -s localhost:9423"]
